// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cache.proto

package cache

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CacheItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheItem) Reset()         { *m = CacheItem{} }
func (m *CacheItem) String() string { return proto.CompactTextString(m) }
func (*CacheItem) ProtoMessage()    {}
func (*CacheItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_cache_1c3f649d81c2417b, []int{0}
}
func (m *CacheItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheItem.Unmarshal(m, b)
}
func (m *CacheItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheItem.Marshal(b, m, deterministic)
}
func (dst *CacheItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheItem.Merge(dst, src)
}
func (m *CacheItem) XXX_Size() int {
	return xxx_messageInfo_CacheItem.Size(m)
}
func (m *CacheItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheItem.DiscardUnknown(m)
}

var xxx_messageInfo_CacheItem proto.InternalMessageInfo

func (m *CacheItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CacheItem) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CacheItem)(nil), "CacheItem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CacheClient is the client API for Cache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CacheClient interface {
	Put(ctx context.Context, in *CacheItem, opts ...grpc.CallOption) (*wrappers.StringValue, error)
	Get(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*CacheItem, error)
	Exists(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
}

type cacheClient struct {
	cc *grpc.ClientConn
}

func NewCacheClient(cc *grpc.ClientConn) CacheClient {

	return &cacheClient{cc}
}

func (c *cacheClient) Put(ctx context.Context, in *CacheItem, opts ...grpc.CallOption) (*wrappers.StringValue, error) {
	out := new(wrappers.StringValue)
	err := c.cc.Invoke(ctx, "/Cache/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) Get(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*CacheItem, error) {
	out := new(CacheItem)
	err := c.cc.Invoke(ctx, "/Cache/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) Exists(ctx context.Context, in *wrappers.StringValue, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/Cache/Exists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheServer is the server API for Cache service.
type CacheServer interface {
	Put(context.Context, *CacheItem) (*wrappers.StringValue, error)
	Get(context.Context, *wrappers.StringValue) (*CacheItem, error)
	Exists(context.Context, *wrappers.StringValue) (*wrappers.BoolValue, error)
}

func RegisterCacheServer(s *grpc.Server, srv CacheServer) {
	s.RegisterService(&_Cache_serviceDesc, srv)
}

func _Cache_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cache/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Put(ctx, req.(*CacheItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Get(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrappers.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cache/Exists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Exists(ctx, req.(*wrappers.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Cache",
	HandlerType: (*CacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Cache_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Cache_Get_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _Cache_Exists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache.proto",
}

func init() { proto.RegisterFile("cache.proto", fileDescriptor_cache_1c3f649d81c2417b) }

var fileDescriptor_cache_1c3f649d81c2417b = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4e, 0x4c, 0xce,
	0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4b, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5,
	0x07, 0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0xcb, 0x8b, 0x12, 0x0b, 0x0a, 0x52, 0x8b, 0x8a, 0x21, 0xf2,
	0x4a, 0xfa, 0x5c, 0x9c, 0xce, 0x20, 0xe5, 0x9e, 0x25, 0xa9, 0xb9, 0x42, 0x7c, 0x5c, 0x4c, 0x99,
	0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x29,
	0x89, 0x25, 0x89, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0xb6, 0xd1, 0x66, 0x46, 0x2e,
	0x56, 0xb0, 0x0e, 0x21, 0x43, 0x2e, 0xe6, 0x80, 0xd2, 0x12, 0x21, 0x2e, 0x3d, 0xb8, 0x01, 0x52,
	0x32, 0x7a, 0x10, 0xeb, 0xf4, 0x60, 0xd6, 0xe9, 0x05, 0x97, 0x14, 0x65, 0xe6, 0xa5, 0x87, 0x25,
	0xe6, 0x94, 0xa6, 0x2a, 0x31, 0x80, 0xb4, 0xb8, 0xa7, 0x96, 0x08, 0xe1, 0x55, 0x26, 0x85, 0x64,
	0xa0, 0x12, 0x83, 0x90, 0x0b, 0x17, 0x9b, 0x6b, 0x45, 0x66, 0x71, 0x49, 0x31, 0x01, 0x5d, 0x52,
	0x18, 0xb2, 0x4e, 0xf9, 0xf9, 0x39, 0x50, 0x8b, 0x93, 0xd8, 0xc0, 0xa2, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x56, 0x3e, 0x9a, 0x23, 0x1c, 0x01, 0x00, 0x00,
}
