---
builds:
  -
    env:
      - CGO_ENABLED=0
    binary: cache
    ldflags:
      - -s -w -X main.version={{.Version}}

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

snapshot:
  name_template: "{{ .Tag }}"

dockers:
  -
    goos: linux
    dockerfile: Dockerfile
    binary: cache
    image_templates:
      - "nicholasjackson/emojify-cache:latest"
      - "nicholasjackson/emojify-cache:{{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
