---
builds:
- ldflags:
  - -s -w -X "main.version={{.Version}}"
  binary: emojify-cache
  goos:
  - linux
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0

dockers:
-
  binaries:
    - emojify-cache
  goos: linux
  goarch: amd64
  dockerfile: Dockerfile
  image_templates:
  - "nicholasjackson/emojify-cache:latest"
  - "nicholasjackson/emojify-cache:{{.Tag}}"
  - "nicholasjackson/emojify-cache:{{.Commit}}"
